# -*- coding: utf-8 -*-
"""work 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcrQqLQTYAU3QKXaoBS_6sTraXNQP7u7
"""



names=["Kagetera" , "John" , "Peter" , "Alex", "Claude"]
names.append("RUGAMBA")
names.append("UOK")
names.append("Joseph")
names.sort()
print(names)